version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=budget_app
      - JWT_SECRET=your-secret-key-here
      - JWT_EXPIRATION=24h
    depends_on:
      - db
    networks:
      - budget-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network

volumes:
  postgres_data:

networks:
  budget-network:
    driver: bridge
